[tool.poetry]
name = "localai"
version = "0.1.0"
description = ""
authors = ["chvckn0rri5 <chvckn0rri5@frenversity.online>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.3.24"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
